repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check src/ tests/
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format-check
        name: ruff-format-check
        entry: uv run ruff format --check src/ tests/
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy-check
        name: mypy-check
        entry: uv run mypy src/ --ignore-missing-imports --show-error-codes
        language: system
        pass_filenames: false
        always_run: true
